### ISSUE TITLE
Node.js - non intuitional replacing in transform()

### ISSUE THREAD

**Issue by syucream** [GoogleCloudPlatform/rcloadenv#14]
I've encountered  non intuitional variable name replacing from `-` to `_`:
For example, when there is a variable name `foo-bar-baz`, `transform()` returns `foo_bar-baz` because `String.prototype.replace()` replaces only a first element.
I prefer to 1) remove the replacing (a return value is `foo-bar-baz`) or 2) replace all elements(a return value is `foo_bar_baz`). What do you think about?

#### Environment details

  - OS: macOS
  - rcloadenv version: 
  - rcloadenv language: Node.js
  -  version: 0.2.1

#### Steps to reproduce

- Its not a bug.

**Comment by tswast** [comment]
![status: inactive](https://img.shields.io/badge/status-inactive-red.svg)

This project is no longer actively developed or maintained.

For new work on this check out the [Secret Manager API](https://cloud.google.com/secret-manager/).
